# Generated by Django 5.1.6 on 2026-03-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Messages', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Chat session', 'verbose_name_plural': 'Chat session'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'Sistem')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='tokens_used',
            field=models.IntegerField(default=0, help_text='Tokens needed'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='model_used',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='New Chat', max_length=200),
        ),
    ]
