# Generated by Django 5.1.6 on 2026-03-10 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фонда')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Общая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, verbose_name='Тикер')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('asset_type', models.CharField(default='stock', max_length=20, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма вложения')),
                ('color', models.CharField(default='#6EE7B7', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('price_at_add', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='simulator.fund')),
            ],
            options={
                'verbose_name': 'Актив фонда',
                'verbose_name_plural': 'Активы фонда',
                'ordering': ['added_at'],
            },
        ),
    ]
