# Generated by Django 5.1.6 on 2026-03-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['-created_at'], 'verbose_name': 'Funds', 'verbose_name_plural': 'Funds'},
        ),
        migrations.AlterModelOptions(
            name='fundasset',
            options={'ordering': ['added_at'], 'verbose_name': 'Fund asset', 'verbose_name_plural': 'Fund asset'},
        ),
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Fund name'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='General amount'),
        ),
        migrations.AlterField(
            model_name='fundasset',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Investment amount'),
        ),
        migrations.AlterField(
            model_name='fundasset',
            name='asset_type',
            field=models.CharField(default='stock', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fundasset',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fundasset',
            name='ticker',
            field=models.CharField(max_length=20, verbose_name='Ticker'),
        ),
    ]
