# Generated by Django 5.1.6 on 2026-01-08 19:15

import apps.users.storage_backends
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import utils.supabase_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('picture', models.FileField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='challenges'), upload_to='challenges/', verbose_name='Picture')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('points', models.IntegerField(default=100, verbose_name='Points')),
                ('button_add_name', models.CharField(max_length=50, verbose_name='Button add name')),
                ('button_view_name', models.CharField(max_length=50, verbose_name='Button view name')),
                ('picture_base64', models.TextField(blank=True, null=True)),
                ('min_answers_required', models.PositiveIntegerField(default=1, verbose_name='Minimum number of answers required')),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeUserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_secondary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChitChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Would you rather?', help_text='Fill the title', max_length=500, verbose_name='Title')),
                ('points', models.PositiveIntegerField(default=100)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Chit Chat',
                'verbose_name_plural': 'Chit Chats',
            },
        ),
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fact_description', models.TextField()),
                ('points', models.PositiveIntegerField(default=25)),
                ('photo', models.ImageField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='photos'), upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_base64', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('term', models.CharField(max_length=100, verbose_name='Term')),
                ('explanation', models.TextField(verbose_name='Explanation')),
                ('color', models.CharField(choices=[('#FF7B7730', '#FF7B7730'), ('#FFC6D4', '#FFC6D4'), ('#FF7B7763', '#FF7B7763'), ('#FFE37F63', '#FFE37F63')], max_length=10, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, help_text='Defines in what order this item appears.', verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Glossary',
                'verbose_name_plural': 'Glossary',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Quizzes',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('points_needed', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Schools',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_file', models.FileField(storage=apps.users.storage_backends.StorjVideoStorage(), upload_to='')),
                ('filename', models.CharField(max_length=200)),
                ('poster_url', models.ImageField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='posters'), upload_to='posters/')),
                ('poster_base64', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=20)),
                ('points', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, max_length=500, null=True, storage=utils.supabase_storage.SupabaseStorage(bucket_name='profile_pictures'), upload_to='profile_pictures/')),
                ('points_count', models.IntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('focus_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('interests', models.CharField(blank=True, max_length=255, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=70, null=True)),
                ('motivation', models.CharField(blank=True, max_length=255, null=True)),
                ('cities', models.CharField(blank=True, max_length=150, null=True)),
                ('current_focus', models.TextField(blank=True, null=True)),
                ('favorite_media', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, default='Trailblazer', max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(choices=[('text', 'Text Blocks'), ('table', 'Table'), ('nothing', 'Nothing')], default='text', max_length=10, verbose_name='Display type')),
                ('auto_adjust_table', models.BooleanField(default=True, verbose_name='Auto adjust table size')),
                ('cancel_edit_delete', models.BooleanField(default=False, verbose_name='Cancel/Edit/Delete entire challenge')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_settings', to='users.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('name', models.CharField(max_length=255, verbose_name='Element name')),
                ('element', models.CharField(choices=[('input', 'Input'), ('textarea', 'Multiline Input'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('date', 'Date Picker'), ('file', 'File Upload')], max_length=20, verbose_name='Element')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('date', 'Date')], max_length=10, verbose_name='Data type')),
                ('value', models.TextField(blank=True, verbose_name='Value')),
                ('add_other_option', models.BooleanField(default=False, verbose_name='Add variant "Other"')),
                ('show_after_confirm', models.BooleanField(default=False, verbose_name='Show after condition is done')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='users.challenge', verbose_name='Challenge')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('file', models.FileField(storage=apps.users.storage_backends.StorjVideoStorage(), upload_to='usersvideo')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.challengeelement')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.challengeuserattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeUserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choices', to='users.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_choices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge | User choice',
                'verbose_name_plural': 'Challenge | User choices',
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.AddField(
            model_name='challengeuserattempt',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='users.challengeuserchoice'),
        ),
        migrations.CreateModel(
            name='ChitChatOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.CharField(max_length=200, verbose_name='Option 1')),
                ('option_2', models.CharField(max_length=200, verbose_name='Option 2')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='users.chitchat')),
            ],
            options={
                'verbose_name': 'Options Table',
                'verbose_name_plural': 'Options Tables',
            },
        ),
        migrations.CreateModel(
            name='ChitChatUserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chit_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chitchat', verbose_name='ChitChat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chit Chat | User Choice',
                'verbose_name_plural': 'Chit Chat | User Choices',
                'unique_together': {('user', 'chit_chat')},
            },
        ),
        migrations.CreateModel(
            name='ChitChatAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name="User's Answer")),
                ('option_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chitchatoption', verbose_name='Option Pair')),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.chitchatuserchoice', verbose_name="User's ChitChat Choice")),
            ],
            options={
                'verbose_name': 'Chit Chat | Single Answer',
                'verbose_name_plural': 'Chit Chat | Single Answers',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('things_first', 'First Moves'), ('levers', 'The Levers'), ('power_portfolio', 'Power Portfolio'), ('playbook', "The Playbook (IRL How-To's)"), ('capital_cash', 'Capital Beyond Cash'), ('money_sports', 'Money & Sports'), ('new_ventures', 'New Ventures'), ('rel_money', 'Relationships & Money')], default='things_first', max_length=50, verbose_name='Page')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display on the page', verbose_name='Display order')),
                ('poster_base64', models.TextField(blank=True, editable=False, help_text='Filled automatically', null=True, verbose_name='Poster url')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['page', 'order'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='completed_content',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='users.content'),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster_base64', models.TextField(blank=True, editable=False, null=True, verbose_name='Poster Base64')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('image', models.ImageField(blank=True, null=True, storage=utils.supabase_storage.SupabaseStorage(bucket_name='quiz_images'), upload_to='quiz_images/')),
                ('question_type', models.CharField(choices=[('input', 'Input'), ('multiple', 'Multiple Choice'), ('single', 'One Answer')], max_length=10)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated options (only for multiple or one answer)')),
                ('correct_answers', models.TextField(help_text='Comma-separated correct answers (match options exactly)')),
                ('points', models.PositiveIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizUserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz | User Choice',
                'verbose_name_plural': 'Quiz | User Choices',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(default=' ')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quizquestion')),
                ('quiz_user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.quizuserchoice')),
            ],
        ),
        migrations.CreateModel(
            name='TableColumnSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Column title')),
                ('cancel_edit_delete', models.BooleanField(default=False, verbose_name='Cancel/Edit/Delete field')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.challengeelement', verbose_name='Field to display')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='users.challengedisplaysettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TextFieldDisplayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.challengeelement')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='users.challengedisplaysettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_school_name', models.CharField(blank=True, max_length=150, null=True)),
                ('graduation_year', models.CharField(max_length=4)),
                ('assigned_code', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.schools')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type', 'object_id'], name='users_conte_content_5f256a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='quizuserchoice',
            unique_together={('user', 'quiz')},
        ),
    ]
