# Generated by Django 5.1.6 on 2025-04-07 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Would you rather?', help_text='Enter your question', max_length=500, verbose_name='Title')),
                ('points', models.PositiveIntegerField(default='0')),
            ],
            options={
                'verbose_name': 'Chit Chat',
                'verbose_name_plural': 'Chit Chats',
            },
        ),
        migrations.CreateModel(
            name='ChitChatOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.CharField(max_length=200, verbose_name='Option 1')),
                ('option_2', models.CharField(max_length=200, verbose_name='Option 2')),
            ],
            options={
                'verbose_name': 'Options Table',
                'verbose_name_plural': 'Options Tables',
            },
        ),
        migrations.CreateModel(
            name='ChitChatUserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=200, verbose_name='Chosen option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User choice',
                'verbose_name_plural': 'User choices',
            },
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='duration',
            new_name='time_period',
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type', 'object_id'], name='users_conte_content_5f256a_idx'),
        ),
        migrations.AddField(
            model_name='chitchatoption',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='users.chitchat'),
        ),
        migrations.AddField(
            model_name='chitchatuserchoice',
            name='chit_chat',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.chitchat', verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='chitchatuserchoice',
            name='option_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chitchatoption', verbose_name='Options'),
        ),
        migrations.AddField(
            model_name='chitchatuserchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='chitchatuserchoice',
            unique_together={('user', 'chit_chat', 'option_pair')},
        ),
    ]
