# Generated by Django 5.1.6 on 2026-01-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('theme_color', models.CharField(help_text='Например: #FD7981', max_length=20)),
                ('icon_svg', models.TextField(help_text='SVG код иконки')),
                ('page_key', models.CharField(help_text='things_first, levers, playbook и т.д.', max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
