# Generated by Django 5.1.6 on 2025-04-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chitchat_chitchatoption_chitchatuserchoice_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chitchatuserchoice',
            unique_together={('user', 'chit_chat')},
        ),
        migrations.AddField(
            model_name='chitchatuserchoice',
            name='choices',
            field=models.JSONField(default=dict, verbose_name='Selected options'),
        ),
        migrations.AlterField(
            model_name='chitchatuserchoice',
            name='chit_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chitchat', verbose_name='ChitChat'),
        ),
        migrations.RemoveField(
            model_name='chitchatuserchoice',
            name='option_pair',
        ),
        migrations.RemoveField(
            model_name='chitchatuserchoice',
            name='selected_option',
        ),
    ]
