# Generated by Django 5.1.6 on 2026-01-20 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='content',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='users.page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='content',
            name='poster_base64',
            field=models.TextField(blank=True, editable=False, help_text='Filled automatically for video content', null=True, verbose_name='Poster url'),
        ),
        migrations.AlterField(
            model_name='page',
            name='icon_svg',
            field=models.TextField(help_text='SVG icon'),
        ),
        migrations.AlterField(
            model_name='page',
            name='theme_color',
            field=models.CharField(help_text='For example: #FD7981', max_length=20),
        ),
    ]
