# Generated by Django 5.1.6 on 2025-04-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_chitchatuserchoice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chitchatuserchoice',
            options={'verbose_name': 'Chit Chat | User choice', 'verbose_name_plural': 'Chit Chat | User choice'},
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='points',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='required_money',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='time_period',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('MY_GOALS', 'My Goals'), ('SUBS', 'Subs - Time to Clean Up!'), ('TRACK_EXPENSES', 'Track your Expenses'), ('START_INVESTING', 'Start Investing'), ('MONEY_DATE', 'Money Date with a Friend')], default='My Goals', max_length=20),
        ),
        migrations.AlterField(
            model_name='chitchat',
            name='title',
            field=models.CharField(default='Would you rather?', help_text="This is just for you, users won't see this title", max_length=500, verbose_name='Title'),
        ),
    ]
