# Generated by Django 5.1.6 on 2025-04-08 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0004_alter_chitchatuserchoice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('friend_name', models.CharField(max_length=255)),
                ('friend_email', models.EmailField(max_length=254)),
                ('target_date', models.DateField()),
                ('celebrating_idea', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyGoalsAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('goal_description', models.TextField()),
                ('money_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_period', models.CharField(choices=[('SHORT', 'Short-term'), ('MID', 'Mid-term'), ('LONG', 'Long-term')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StartInvestingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('reason_description', models.TextField()),
                ('first_investment', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubsCleanupAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeling', models.CharField(choices=[('LOVE', 'Love'), ('LIKE', 'Like'), ('MEH', 'Meh')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrackExpensesAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expense', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('NEEDS', 'Needs'), ('WANTS', 'Wants'), ('SAVING', 'Saving/Investing'), ('MISC', 'Miscellaneous')], max_length=15)),
                ('surprize_thing', models.TextField()),
                ('tweak_thing', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeUserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.challenge')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
