# Generated by Django 5.1.6 on 2026-01-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_content_content_type_alter_content_object_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='page',
            name='icon_svg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_key',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='theme_color',
            field=models.CharField(default='#FD7981', max_length=20),
        ),
    ]
