# Generated by Django 5.1.6 on 2025-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_moneydateanswer_mygoalsanswer_startinvestinganswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
