# Generated by Django 5.1.6 on 2025-04-08 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_challenge_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeuserchoice',
            options={'verbose_name': 'Challenge | User choice', 'verbose_name_plural': 'Challenge | User choices'},
        ),
        migrations.AlterUniqueTogether(
            name='challengeuserchoice',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddField(
            model_name='challengeuserchoice',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Submitted data'),
        ),
        migrations.AddField(
            model_name='challengeuserchoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='challengeuserchoice',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.challenge', verbose_name='Challenge'),
        ),
        migrations.AlterField(
            model_name='challengeuserchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='chitchat',
            name='title',
            field=models.CharField(default='Would you rather?', help_text='Fill the title', max_length=500, verbose_name='Title'),
        ),
        migrations.RemoveField(
            model_name='challengeuserchoice',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='challengeuserchoice',
            name='object_id',
        ),
    ]
