# Generated by Django 5.1.6 on 2026-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_content_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cities',
        ),
        migrations.AddField(
            model_name='user',
            name='curr_city',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hometowm',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
