# Generated by Django 5.1.6 on 2026-02-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_cities_user_curr_city_user_hometowm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='focus_of_study',
            new_name='current_vibe',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hobbies',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='interests',
            new_name='next_move',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='motivation',
            new_name='you_today',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_focus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_media',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
