# Generated by Django 5.1.6 on 2025-04-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_challengeuserchoice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('name', models.CharField(max_length=255, verbose_name='Element name')),
                ('element', models.CharField(choices=[('input', 'Input'), ('textarea', 'Multiline Input'), ('radio', 'Radio Buttons')], max_length=20, verbose_name='Element')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('float', 'Float')], max_length=10, verbose_name='Data type')),
                ('value', models.TextField(blank=True, verbose_name='Value')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='challengeuserchoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='challengeuserchoice',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengeuserchoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='MoneyDateAnswer',
        ),
        migrations.DeleteModel(
            name='MyGoalsAnswer',
        ),
        migrations.DeleteModel(
            name='StartInvestingAnswer',
        ),
        migrations.DeleteModel(
            name='SubsCleanupAnswer',
        ),
        migrations.DeleteModel(
            name='TrackExpensesAnswer',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='challenge_type',
        ),
        migrations.AddField(
            model_name='challenge',
            name='instructions',
            field=models.TextField(default=' ', verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='picture',
            field=models.ImageField(default=' ', upload_to='challenges/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default='0', verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='challengeelement',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='users.challenge', verbose_name='Challenge'),
        ),
        migrations.DeleteModel(
            name='ChallengeUserChoice',
        ),
    ]
