# Generated by Django 5.1.6 on 2026-02-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_focus_of_study_user_current_vibe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hometowm',
            new_name='hometown',
        ),
    ]
