# Generated by Django 5.1.6 on 2025-04-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_challengeelement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='button_add_name',
            field=models.CharField(default=' ', max_length=50, verbose_name='Button add name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='button_view_name',
            field=models.CharField(default=' ', max_length=50, verbose_name='Button view name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='instructions',
            field=models.TextField(verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='picture',
            field=models.ImageField(upload_to='challenges/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(verbose_name='Points'),
        ),
    ]
