# Generated by Django 5.1.6 on 2025-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_challenge_button_add_name_challenge_button_view_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='picture_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
