# Generated by Django 5.1.6 on 2026-02-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_hometowm_user_hometown'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='always_available',
            field=models.BooleanField(default=False, help_text='If checked, this content is available regardless of order', verbose_name='Always available'),
        ),
    ]
