# Generated by Django 5.1.6 on 2025-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_challenge_picture_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeelement',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('date', 'Date Picker')], max_length=10, verbose_name='Data type'),
        ),
    ]
