# Generated by Django 5.1.6 on 2026-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_content_always_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='condition',
            field=models.CharField(blank=True, help_text='Condition that must be met for this content to be available', max_length=100, null=True, verbose_name='Access condition'),
        ),
    ]
