# Generated by Django 5.1.6 on 2025-04-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_challengeelement_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeelement',
            name='element',
            field=models.CharField(choices=[('input', 'Input'), ('textarea', 'Multiline Input'), ('radio', 'Radio Buttons'), ('date', 'Date Picker')], max_length=20, verbose_name='Element'),
        ),
        migrations.AlterField(
            model_name='challengeelement',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('date', 'Date')], max_length=10, verbose_name='Data type'),
        ),
        migrations.CreateModel(
            name='ChallengeDisplayBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Block title')),
                ('display_type', models.CharField(choices=[('table', 'Table'), ('card', 'Card'), ('text', 'Text block')], default='table', max_length=20, verbose_name='Display type')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_blocks', to='users.challenge')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeDisplayField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Field Label')),
                ('field_key', models.CharField(help_text="Must match the key in user's data", max_length=100)),
                ('display_format', models.CharField(blank=True, help_text='e.g. $#, plain text, date', max_length=50)),
                ('color_rule', models.CharField(choices=[('none', 'No color'), ('positive', 'Green if positive'), ('negative', 'Red if negative'), ('custom', 'Custom condition')], default='none', max_length=20)),
                ('custom_condition', models.TextField(blank=True, help_text='Python condition, e.g. value > 50')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='users.challengedisplayblock')),
            ],
        ),
    ]
