# Generated by Django 5.1.6 on 2026-04-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_content_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='has_conditions',
            field=models.BooleanField(default=False, help_text='Internal field for condition handling', verbose_name='Has conditions'),
        ),
    ]
