# Generated by Django 5.1.6 on 2026-05-14 21:18

import utils.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_content_has_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='static_images'), upload_to='static_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Static Image',
                'verbose_name_plural': 'Static Images',
            },
        ),
    ]
