# Generated by Django 5.1.6 on 2025-04-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_challengeelement_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengedisplayblock',
            name='display_type',
            field=models.CharField(choices=[('table', 'Table'), ('card', 'Card')], default='table', max_length=20, verbose_name='Display type'),
        ),
    ]
