# Generated by Django 5.1.6 on 2025-04-09 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_challengedisplayblock_display_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengedisplayfield',
            name='block',
        ),
        migrations.CreateModel(
            name='ChallengeUserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choices', to='users.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_choices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.challengeelement')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.challengeuserchoice')),
            ],
        ),
        migrations.DeleteModel(
            name='ChallengeDisplayBlock',
        ),
        migrations.DeleteModel(
            name='ChallengeDisplayField',
        ),
    ]
