# Generated by Django 5.1.6 on 2026-06-26 08:58

import django.core.validators
import utils.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_staticimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='icon_svg',
            field=models.FileField(blank=True, help_text='Upload SVG only (.svg)', null=True, storage=utils.supabase_storage.SupabaseStorage(bucket_name='pages'), upload_to='pages-icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
