# Generated by Django 5.1.6 on 2025-04-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_challengedisplayfield_block_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeuserchoice',
            options={'verbose_name': 'Challenge | User choice', 'verbose_name_plural': 'Challenge | User choices'},
        ),
        migrations.AlterModelOptions(
            name='chitchatuserchoice',
            options={'verbose_name': 'Chit Chat | User Choice', 'verbose_name_plural': 'Chit Chat | User Choices'},
        ),
        migrations.RemoveField(
            model_name='chitchatuserchoice',
            name='choices',
        ),
        migrations.CreateModel(
            name='ChitChatAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name="User's Answer")),
                ('option_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chitchatoption', verbose_name='Option Pair')),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.chitchatuserchoice', verbose_name="User's ChitChat Choice")),
            ],
            options={
                'verbose_name': 'Chit Chat | Single Answer',
                'verbose_name_plural': 'Chit Chat | Single Answers',
            },
        ),
    ]
