# Generated by Django 5.1.6 on 2026-07-26 09:25

import utils.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_page_icon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='poster_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='poster_url',
            field=models.ImageField(blank=True, null=True, storage=utils.supabase_storage.SupabaseStorage(bucket_name='posters'), upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='chitchat',
            name='poster_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chitchat',
            name='poster_url',
            field=models.ImageField(blank=True, null=True, storage=utils.supabase_storage.SupabaseStorage(bucket_name='posters'), upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='chitchat',
            name='title',
            field=models.CharField(default='Would you rather?', max_length=500, verbose_name='Title'),
        ),
    ]
