# Generated by Django 5.1.6 on 2025-04-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_challengeuserchoice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(choices=[('text', 'Text Blocks'), ('table', 'Table View')], default='text', max_length=10)),
                ('text_fields_order', models.JSONField(blank=True, help_text='Порядок полей для текстового отображения', null=True)),
                ('table_column_count', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_row_count', models.BooleanField(default=True)),
                ('use_column_headers', models.BooleanField(default=True)),
                ('column_headers', models.JSONField(blank=True, null=True)),
                ('column_field_mapping', models.JSONField(blank=True, null=True)),
                ('row_colors_by_field', models.JSONField(blank=True, help_text="{'love_level': {'High': '#ffaaaa'}}", null=True)),
                ('custom_category_view', models.BooleanField(default=False)),
                ('category_field', models.CharField(blank=True, max_length=100, null=True)),
                ('value_field', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_settings', to='users.challenge')),
            ],
        ),
    ]
