# Generated by Django 5.1.6 on 2025-04-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_challengedisplaysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='auto_row_count',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='category_field',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='column_field_mapping',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='column_headers',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='custom_category_view',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='row_colors_by_field',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='table_column_count',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='text_fields_order',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='use_column_headers',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='value_field',
        ),
        migrations.CreateModel(
            name='TextDisplayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('display_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_orders', to='users.challengedisplaysettings')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.challengeelement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
