# Generated by Django 5.1.6 on 2025-04-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_challengedisplaysettings_auto_row_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdisplayorder',
            name='display_settings',
        ),
        migrations.RemoveField(
            model_name='textdisplayorder',
            name='element',
        ),
        migrations.DeleteModel(
            name='ChallengeDisplaySettings',
        ),
        migrations.DeleteModel(
            name='TextDisplayOrder',
        ),
    ]
