# Generated by Django 5.1.6 on 2025-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_textdisplayorder_display_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='block_display_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='Fields for block view'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='display_mode',
            field=models.CharField(choices=[('block', 'Text block'), ('table', 'Table')], default='block', max_length=10, verbose_name='Display mode'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='table_config',
            field=models.JSONField(blank=True, null=True, verbose_name='Table config'),
        ),
    ]
