# Generated by Django 5.1.6 on 2025-04-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_challenge_block_display_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='block_display_fields',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='display_mode',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='table_config',
        ),
    ]
