# Generated by Django 5.1.6 on 2025-04-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_challengedisplaysettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengedisplaysettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='column_titles',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='field_mapping',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='fields_to_show',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='num_columns',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='num_rows',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='row_color_rules',
        ),
        migrations.RemoveField(
            model_name='challengedisplaysettings',
            name='row_titles',
        ),
        migrations.AlterField(
            model_name='challengedisplaysettings',
            name='auto_adjust_table',
            field=models.BooleanField(default=True, verbose_name='Auto adjust table size'),
        ),
        migrations.CreateModel(
            name='TableColumnSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Column title')),
                ('order', models.PositiveIntegerField()),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.challengeelement', verbose_name='Field to display')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='users.challengedisplaysettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TextFieldDisplayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.challengeelement')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='users.challengedisplaysettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
