# Generated by Django 5.1.6 on 2025-04-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_tablecolumnsetting_custom_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeuserchoice',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='challengeuseranswer',
            name='choice',
        ),
        migrations.AlterUniqueTogether(
            name='challengeuserchoice',
            unique_together={('user', 'challenge')},
        ),
        migrations.CreateModel(
            name='ChallengeUserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='users.challengeuserchoice')),
            ],
        ),
        migrations.AddField(
            model_name='challengeuseranswer',
            name='attempt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.challengeuserattempt'),
            preserve_default=False,
        ),
    ]
