# Generated by Django 5.1.6 on 2025-04-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_submitted_at_challengeuserchoice_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablecolumnsetting',
            name='custom_values',
        ),
        migrations.RemoveField(
            model_name='tablecolumnsetting',
            name='use_field',
        ),
        migrations.AlterField(
            model_name='tablecolumnsetting',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.challengeelement', verbose_name='Field to display'),
        ),
    ]
