# Generated by Django 5.1.6 on 2025-04-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_tablecolumnsetting_custom_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRadioColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Option value')),
                ('color', models.CharField(help_text='Например: red, #FF0000, rgb(255,0,0)', max_length=20, verbose_name='CSS color')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_options', to='users.challengeelement')),
            ],
        ),
    ]
