# Generated by Django 5.1.6 on 2025-04-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_challengeradiocoloroption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeRadioColorOption',
        ),
    ]
