# Generated by Django 5.1.6 on 2025-04-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_delete_challengeradiocoloroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeuserattempt',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
