# Generated by Django 5.1.6 on 2025-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_challengeuserattempt_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='min_answers_required',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimum number of answers required'),
        ),
    ]
