# Generated by Django 5.1.6 on 2025-04-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_tablecolumnsetting_cancel_edit_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengedisplaysettings',
            name='cancel_edit_delete',
            field=models.BooleanField(default=False, verbose_name='Cancel/Edit/Delete entire challenge'),
        ),
    ]
