# Generated by Django 5.1.6 on 2025-04-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_challengedisplaysettings_cancel_edit_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeelement',
            name='show_after_confirm',
            field=models.BooleanField(default=False, verbose_name='Show after condition is done'),
        ),
    ]
