# Generated by Django 5.1.6 on 2025-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_challengeelement_show_after_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeuseranswer',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
    ]
