# Generated by Django 5.1.6 on 2025-04-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_challengeuseranswer_is_secondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeuseranswer',
            name='is_secondary',
        ),
        migrations.AddField(
            model_name='challengeuserattempt',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
    ]
