# Generated by Django 5.1.6 on 2025-04-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_schools_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
