# Generated by Django 5.1.6 on 2025-04-23 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_schools_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_school_name', models.CharField(blank=True, max_length=150, null=True)),
                ('graduation_year', models.CharField(max_length=4)),
                ('assigned_code', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.schools')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
