# Generated by Django 5.1.6 on 2025-04-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_userschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschool',
            name='other_school_name',
        ),
    ]
