# Generated by Django 5.1.6 on 2025-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_userschool_other_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschool',
            name='other_school_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
