# Generated by Django 5.1.6 on 2025-04-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_userschool_other_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('question_type', models.CharField(choices=[('input', 'Input'), ('multiple', 'Multiple Choice'), ('single', 'One Answer')], max_length=10)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated options (only for multiple or one answer)')),
                ('correct_answers', models.TextField(help_text='Comma-separated correct answers (match options exactly)')),
                ('points', models.PositiveIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.quiz')),
            ],
        ),
    ]
