# Generated by Django 5.1.6 on 2025-04-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_quiz_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
