# Generated by Django 5.1.6 on 2025-04-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_quizuseranswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizUserAnswer',
            new_name='QuizUserChoice',
        ),
    ]
