# Generated by Django 5.1.6 on 2025-04-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_rename_quizuseranswer_quizuserchoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizuserchoice',
            options={'verbose_name': 'Quiz | User Choice', 'verbose_name_plural': 'Quiz | User Choices'},
        ),
        migrations.AlterUniqueTogether(
            name='quizuserchoice',
            unique_together={('user', 'quiz')},
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(default=' ')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quizquestion')),
                ('quiz_user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.quizuserchoice')),
            ],
        ),
        migrations.RemoveField(
            model_name='quizuserchoice',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quizuserchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizuserchoice',
            name='user_answer',
        ),
    ]
