# Generated by Django 5.1.6 on 2025-04-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_quizuserchoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuserchoice',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
