# Generated by Django 5.1.6 on 2025-05-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_quizuserchoice_points_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.TextField(blank=True, default='Trailblazer', null=True),
        ),
    ]
