# Generated by Django 5.1.6 on 2025-05-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, default='Trailblazer', max_length=20, null=True),
        ),
    ]
