# Generated by Django 5.1.6 on 2025-05-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('points_needed', models.PositiveIntegerField()),
            ],
        ),
    ]
