# Generated by Django 5.1.6 on 2025-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_userreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.CharField(choices=[('its_time', 'It’s time we talk money'), ('rich_girl', 'Rich girl moves'), ('you_do_you', 'You do YOU'), ('levers', 'The Levers'), ('portfolio', 'The Power Portfolio')], default='its_time', max_length=50, verbose_name='Page'),
        ),
    ]
