# Generated by Django 5.1.6 on 2025-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_user_motivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.CharField(choices=[('its_time', 'First Moves'), ('rich_girl', 'The Levers'), ('you_do_you', 'Power Portfolio'), ('levers', "The Playbook (IRL How-To's)"), ('portfolio', 'Capital Beyond Cash')], default='its_time', max_length=50, verbose_name='Page'),
        ),
    ]
