# Generated by Django 5.1.6 on 2025-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
