# Generated by Django 5.1.6 on 2025-05-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_user_supabase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.URLField(),
        ),
    ]
