# Generated by Django 5.1.6 on 2025-05-30 19:13

import utils.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_video_poster_url_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=utils.supabase_storage.SupabaseStorage(bucket_name='media'), upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster_url',
            field=models.ImageField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='photos'), upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='video_sources'), upload_to='videos/'),
        ),
    ]
