# Generated by Django 5.1.6 on 2025-06-04 14:01

import django.core.validators
import utils.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_video_poster_url_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quizzes', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='regards',
            options={'verbose_name': 'Rewards', 'verbose_name_plural': 'Rewards'},
        ),
        migrations.AlterModelOptions(
            name='schools',
            options={'verbose_name': 'Schools', 'verbose_name_plural': 'Schools'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supabase_id',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='picture',
            field=models.ImageField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='challenges'), upload_to='challenges/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.CharField(choices=[('things_first', 'First Moves'), ('levers', 'The Levers'), ('power_portfolio', 'Power Portfolio'), ('playbook', "The Playbook (IRL How-To's)"), ('capital_cash', 'Capital Beyond Cash'), ('money_sports', 'Money & Sports'), ('new_ventures', 'New Ventures'), ('rel_money', 'Relationships & Money')], default='its_time', max_length=50, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='funfact',
            name='photo',
            field=models.ImageField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='photos'), upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.supabase_storage.SupabaseStorage(bucket_name='quiz_images'), upload_to='quiz_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=utils.supabase_storage.SupabaseStorage(bucket_name='profile_pictures'), upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster_url',
            field=models.ImageField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='posters'), upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='video_sources'), upload_to='videos/'),
        ),
    ]
