# Generated by Django 5.1.6 on 2025-06-06 14:33

import utils.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_alter_quiz_options_alter_regards_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeuseranswer',
            name='file',
            field=models.FileField(blank=True, null=True, storage=utils.supabase_storage.SupabaseStorage(bucket_name='challenge_uploads'), upload_to='challenge_uploads/'),
        ),
        migrations.AlterField(
            model_name='challengedisplaysettings',
            name='display_type',
            field=models.CharField(choices=[('text', 'Text Blocks'), ('table', 'Table'), ('nothing', 'Nothing')], default='text', max_length=10, verbose_name='Display type'),
        ),
        migrations.AlterField(
            model_name='challengeelement',
            name='element',
            field=models.CharField(choices=[('input', 'Input'), ('textarea', 'Multiline Input'), ('radio', 'Radio Buttons'), ('date', 'Date Picker'), ('file', 'File Upload')], max_length=20, verbose_name='Element'),
        ),
        migrations.AlterField(
            model_name='challengeuseranswer',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
