# Generated by Django 5.1.6 on 2025-05-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_video_thumbnail_alter_video_poster_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
