# Generated by Django 5.1.6 on 2025-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_challengeuseranswer_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeelement',
            name='add_other_option',
            field=models.BooleanField(default=False, verbose_name='Add variant "Other"'),
        ),
        migrations.AlterField(
            model_name='challengeelement',
            name='element',
            field=models.CharField(choices=[('input', 'Input'), ('textarea', 'Multiline Input'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('date', 'Date Picker'), ('file', 'File Upload')], max_length=20, verbose_name='Element'),
        ),
        migrations.AlterField(
            model_name='challengeuseranswer',
            name='answer',
            field=models.TextField(),
        ),
    ]
