# Generated by Django 5.1.6 on 2025-06-11 14:36

import utils.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_challengeelement_add_other_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='picture',
            field=models.FileField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='challenges'), upload_to='challenges/', verbose_name='Picture'),
        ),
    ]
