# Generated by Django 5.1.6 on 2025-06-18 09:11

import storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_challenge_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=storage_backends.StorjVideoStorage(), upload_to=''),
        ),
    ]
