# Generated by Django 5.1.6 on 2025-06-22 15:20

import apps.users.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_challenge_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=apps.users.storage_backends.StorjVideoStorage(), upload_to=''),
        ),
    ]
