# Generated by Django 5.1.6 on 2025-06-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='public_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
