# Generated by Django 5.1.6 on 2025-06-21 15:40

import utils.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_video_public_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='public_video_url',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=utils.supabase_storage.SupabaseStorage(bucket_name='video_sources'), upload_to='videos/'),
        ),
    ]
