# Generated by Django 5.1.6 on 2025-06-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_remove_video_public_video_url_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
