# Generated by Django 5.1.6 on 2025-06-21 16:14

import apps.users.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_video_video_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file_path',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=apps.users.storage_backends.StorjVideoStorage(), upload_to='videos/'),
        ),
    ]
