# Generated by Django 5.1.6 on 2025-06-21 22:48

import apps.users.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_remove_video_video_file_path_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=apps.users.storage_backends.StorjVideoStorage(), upload_to=''),
        ),
    ]
