# Generated by Django 5.1.6 on 2025-06-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_video_filename_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='access_grant_id',
            field=models.CharField(default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
