# Generated by Django 5.1.6 on 2025-06-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_video_access_grant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='access_grant_id',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='filename',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
