# Generated by Django 5.1.6 on 2025-06-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_alter_video_video_file'),
        ('users', '0070_remove_video_access_grant_id_video_video_url_and_more'),
    ]

    operations = [
    ]
