# Generated by Django 5.1.6 on 2025-06-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_merge_20250622_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='video',
            name='filename',
            field=models.CharField(max_length=200),
        ),
    ]
