# Generated by Django 5.1.6 on 2025-06-26 12:11

import apps.users.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_remove_video_video_url_alter_video_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeuseranswer',
            name='file',
            field=models.FileField(default=1, storage=apps.users.storage_backends.StorjVideoStorage(), upload_to='usersvideo'),
            preserve_default=False,
        ),
    ]
