# Generated by Django 5.1.6 on 2025-07-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_alter_challengeuseranswer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeuserchoice',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
