# Generated by Django 5.1.6 on 2025-12-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_alter_content_options_content_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['page', 'order']},
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display on the page', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.CharField(choices=[('things_first', 'First Moves'), ('levers', 'The Levers'), ('power_portfolio', 'Power Portfolio'), ('playbook', "The Playbook (IRL How-To's)"), ('capital_cash', 'Capital Beyond Cash'), ('money_sports', 'Money & Sports'), ('new_ventures', 'New Ventures'), ('rel_money', 'Relationships & Money')], default='things_first', max_length=50, verbose_name='Page'),
        ),
    ]
