# Generated by Django 5.1.6 on 2025-12-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_content_options_alter_content_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('term', models.CharField(max_length=100, verbose_name='Term')),
                ('explanation', models.TextField(verbose_name='Explanation')),
                ('color', models.CharField(choices=[('#FF7B7730', '#FF7B7730'), ('#FFC6D4', '#FFC6D4'), ('#FF7B7763', '#FF7B7763'), ('#FFE37F63', '#FFE37F63')], max_length=10, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, help_text='Defines in what order this item appears.', verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Glossary',
                'verbose_name_plural': 'Glossary',
                'ordering': ['order'],
            },
        ),
    ]
